### ISSUE TITLE
[화면구현] 상품 > result(상품검색결과)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#10]

**Comment by lazca2080** [comment]
DB 설계
담당자 : 박종협
내용 : 상품 > result 화면 구현
시작일 : 2023.02.27
예상 종료일 : 2023.02.28
실제 종료일: 
후기 :

**Comment by lazca2080** [comment]
**체크리스트**

>  - [ ] Jquery UI Date Picker
>  - [ ] 마우스 클릭 시 검색 필터 확장/축소
>  - [ ] 지도 API 삽입
>  - [ ] 페이징 처리
