### ISSUE TITLE
[화면구현] 상품 >reservation(상품예약) > result(상품예약결과)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#13]

**Comment by lazca2080** [comment]
**상품 상품예약결과**

> 담당자 : 박종협
> 내용 : 상품 > reservation(상품예약) > result(상품예약결과)
> 시작일 : 2023.03.03
> 예상 종료일 : 2023.03.04
> 실제 종료일: 
> 후기 :
