### ISSUE TITLE
[화면구현] 마이페이지 > reservation(예약내역) > view(예약내역 상세)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#15]

**Comment by hwangwonjin** [comment]
마이페이지 예약내역 상세 화면 구현

담당자: 황원진
내용: HTML 마이페이지 예약내역 상세 화면 구현
시작일: 2023/02/25
예상 종료일: 2023/02/26
실제 종료일:
후기:

**Comment by hwangwonjin** [comment]
- [ ] 상세내역 인쇄
- [ ] 예약 취소
