### ISSUE TITLE
[화면구현] 마이페이지 > info(나의 정보)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#16]

**Comment by hwangwonjin** [comment]
마이페이지 나의 정보 화면 구현

담당자: 황원진
내용: HTML 마이페이지 나의 정보 화면 구현
시작일: 2023/02/28
예상 종료일: 2023/02/28
실제 종료일:
후기:

**Comment by hwangwonjin** [comment]
- [ ] 프로필사진
- [ ] 소셜 로그인시 표시
