### ISSUE TITLE
[화면구현] 마이페이지 > point(포인트)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#17]

**Comment by hwangwonjin** [comment]
마이페이지 포인트 화면 구현

담당자: 황원진
내용: HTML 마이페이지 포인트 화면 구현
시작일: 2023/02/26
예상 종료일: 2023/02/26
실제 종료일:
후기:

**Comment by hwangwonjin** [comment]
- [ ] 리스트 설정 버튼
- [ ] 리스트
