### ISSUE TITLE
[화면구현] 마이페이지 > pick(나의 찜)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#19]

**Comment by hwangwonjin** [comment]
마이페이지 나의 찜 화면 구현

담당자: 황원진
내용: HTML 마이페이지 나의 찜 화면 구현
시작일: 2023/02/27
예상 종료일: 2023/02/27
실제 종료일:
후기:

**Comment by hwangwonjin** [comment]
- [ ] 리스트
- [ ] 페이징
