### ISSUE TITLE
[화면구현] 마이페이지 > diary(나의 여행일기) > list(목록)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#20]

**Comment by lazca2080** [comment]
**마이페이지 나의 여행일기 목록**

> 담당자 : 황원진, 박종협
> 내용 : my > diary(나의 여행일기) > list(목록)
> 시작일 : 2023.03.03
> 예상 종료일 : 2023.03.04
> 실제 종료일: 2023.03.05
> 후기 : 지도 확장 / 축소 기능 추가로 인해 작업시간이 길어짐
