### ISSUE TITLE
[화면구현] 마이페이지 > diary(나의 여행일기) > write(쓰기)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#22]

**Comment by hwangwonjin** [comment]
마이페이지-나의 여행일기-쓰기 화면 구현

담당자: 황원진
내용: HTML 마이페이지-나의 여행일기-쓰기 화면 구현
시작일: 2023/03/01
예상 종료일: 2023/03/02
실제 종료일:
후기:
