### ISSUE TITLE
[화면구현] 마이페이지 > review(나의 리뷰) > list(목록)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#24]

**Comment by hwangwonjin** [comment]
마이페이지-리뷰-리스트 화면 구현

담당자: 황원진
내용: HTML 마이페이지-리뷰-리스트 화면 구현
시작일: 2023/02/28
예상 종료일: 2023/02/28
실제 종료일:2023/03/01
후기:
