### ISSUE TITLE
[화면구현] 마이페이지 > review(나의 리뷰) > view(보기)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#25]

**Comment by hwangwonjin** [comment]
마이페이지-나의 리뷰 - 보기 화면 구현

담당자: 황원진
내용: HTML 마이페이지-나의 리뷰-보기 화면 구현
시작일: 2023/03/01
예상 종료일: 2023/03/01
실제 종료일:
후기:

**Comment by hwangwonjin** [comment]
- [ ]  슬라이더 형식 사진 표시
- [ ] 목록, 수정 삭제 버튼
