### ISSUE TITLE
[화면구현] 회원 > 메인(main)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#3]

**Comment by Yiwonjeong** [comment]
**** 메인 화면 구현

담당자: 이원정
내용: HTML 메인 화면 구현
시작일: 2023/02/23
예상 종료일: 2023/02/24
실제 종료일: 
후기:

**Comment by Yiwonjeong** [comment]
**체크리스트**

> - [ ] 헤더, 푸터, 메인 레이아웃
> - [ ] 헤더 click down menu (마이페이지, 고객센터)
> - [ ] 바로가기 카테고리 아이콘
