### ISSUE TITLE
[화면구현] 고객센터 > event(이벤트) > view(보기)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#30]

**Comment by 094haley** [comment]
**고객센터 이벤트 보기 화면설계**
> 담당자 : 이해빈
> 내용 : 고개센터 event(이벤트) 보기 화면설계
> 시작일 : 2023/02/26
> 예상 종료일 : 2023/02/27
> 실제 종료일: 
> 후기 :

**Comment by 094haley** [comment]
**체크리스트**

- [ ] 이벤트 내용 출력
- [ ] 토글 기능 
- [ ] 이전글 / 다음글
