### ISSUE TITLE
[화면구현] 고객센터 > faq(자주묻는 질문) > list(목록)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#31]

**Comment by 094haley** [comment]
**고객센터 자주묻는 질문 화면구현**

> 담당자 : 이해빈
> 내용 : 고객센터 faq(자주묻는 질문) 화면구현
> 시작일 : 2023/02/27
> 예상 종료일 : 2023/02/27
> 실제 종료일: 
> 후기 :

**Comment by 094haley** [comment]
**체크리스트**

- [ ] 자주묻는 질문 카테고리
- [ ] 목록출력
