### ISSUE TITLE
[화면구현] 관리자 > product(상품관리) > info(숙소정보) > list(목록)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#38]

**Comment by Yiwonjeong** [comment]
관리자 > 상품관리 > 숙소정보 > 목록 화면 구현

담당자: 이원정
내용: HTML 관리자 메인 화면 구현
시작일: 2023/02/26
예상 종료일: 2023/02/26
실제 종료일:
후기:

**Comment by Yiwonjeong** [comment]
2023/02/26

- [ ]  화면 레이아웃
- [ ]  화면 사이드바
- [ ]  화면 목록 
- [ ]  화면 페이징
