### ISSUE TITLE
[화면구현] 관리자 > product(상품관리) > info(숙소정보) > view(보기)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#39]

**Comment by Yiwonjeong** [comment]
관리자 > 상품관리 > 숙박관리 > 숙소 보기 화면 구현

담당자: 이원정
내용: HTML 관리자 화면 구현 (admin/info/view)
시작일: 2023/02/27
예상 종료일: 2023/02/27
실제 종료일: 2023/02/27
후기: -

**Comment by Yiwonjeong** [comment]
2023/02/27

- [ ]  상품 숙소 보기 화면 구현
