### ISSUE TITLE
[화면구현] 회원 > 로그인(login)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#4]

**Comment by 094haley** [comment]
담당자 : 이해빈
내용 :  회원 > 로그인 (login) 화면설계 
시작일 : 2023.02.24
예상 종료일 : 2023.02.25
실제 종료일: 
후기 :

**Comment by 094haley** [comment]
**체크리스트**

> - [ ]  로고 삽입
> - [ ]  연동 로그인 버튼
> - [ ]  이메일, 비밀번호 입력칸
> - [ ]  유효성 검사 어긋날 시 이메일, 비밀번호 스타일 변경
> - [ ]  로그인 버튼, 비밀번호 재설정, 회원가입

**Comment by 094haley** [comment]
**기능구현시  참고사항**

> 이메일 주소, 비밀번호 입력 DIV 에 inp_error 클래스 속성 추가
> label 속성을 display:none -> display:block으로 변경

**Comment by 094haley** [comment]
** 회의요망 **
- [ ] 로고 이미지 삽입여부 
- [ ]  구글 로그인 배경색
