### ISSUE TITLE
[화면구현] 관리자 > product(상품관리) > info(숙소정보) > modify(수정)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#41]

**Comment by Yiwonjeong** [comment]
관리자 > 상품관리 > 숙소정보 > 수정 화면 구현

담당자: 이원정
내용: HTML 관리자 화면 구현 (admin/info/modify)
시작일: 2023/02/26
예상 종료일: 2023/02/26
실제 종료일: 2023/02/26
후기: 화면 설계는 등록 화면과 겹치기 때문에 큰 어려움이 없었다.

**Comment by Yiwonjeong** [comment]
2023/02/26

- [ ] 상품 숙소 수정 화면 구현
