### ISSUE TITLE
[화면구현] 관리자 > product(상품관리) >review(등록된 리뷰) > list(목록)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#42]

**Comment by Yiwonjeong** [comment]
관리자 > 쿠폰등록

담당자: 이원정
내용: HTML 관리자 리뷰 목록 화면 구현 (admin/review/list)
시작일: 2023/02/28
예상 종료일: 2023/03/01
실제 종료일: 2023/03/01
후기: -

**Comment by Yiwonjeong** [comment]
2023/03/01

- [ ]  관리자 - 상품관리 - 등록된 리뷰 - 목록 화면 구현
