### ISSUE TITLE
[화면구현] 관리자 > product(상품관리) >review(등록된 리뷰) > view(보기)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#43]

**Comment by Yiwonjeong** [comment]
관리자 > 쿠폰등록

담당자: 이원정
내용: HTML 관리자 리뷰 보기 및 답변 화면 구현 (admin/review/view)
시작일: 2023/02/28
예상 종료일: 2023/03/01
실제 종료일: 2023/03/01
후기: 사진 슬라이더 위치 조정하는 데 살짝 어려움이 있었다.
        dialog로 모달 팝업 형태를 새로 만들어 보았다.

**Comment by Yiwonjeong** [comment]
2023/03/01

- [ ] 관리자 - 상품관리 - 등록된 리뷰 - 보기 화면 구현
