### ISSUE TITLE
[화면구현] 관리자 > user(회원관리)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#47]

**Comment by Yiwonjeong** [comment]
관리자 > 회원관리

담당자: 이원정
내용: HTML 관리자 회원관리 화면 구현 (admin/user)
시작일: 2023/03/04
예상 종료일: 2023/03/04
실제 종료일: 2023/03/04
후기: 같은 이름의 클래스를 가진 모달이 여러 개가 되니까 showModa(), close() 함수가 적용되지 않았다. 그래서 우선 해당 페이지는 레이아웃으로 팝업을 만들었다...
