### ISSUE TITLE
[화면구현] 회원 > join(가입구분)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#5]

**Comment by 094haley** [comment]
**회원 가입구분 화면설계**

> 담당자 : 이해빈
> 내용 : 회원 join(가입구분) 화면설계
> 시작일 : 2023/02/25
> 예상 종료일 : 2023/02/25
> 실제 종료일: 
> 후기 :

**Comment by 094haley** [comment]
**체크리스트**

- [ ]  소개문구
- [ ] 일반회원 가입
- [ ] 비즈니스 회원 가입
