### ISSUE TITLE
[화면구현] 회원 > terms(약관동의)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#6]

**Comment by 094haley** [comment]
**회원 약관동의**

> 담당자 : 이해빈
> 내용 : 회원 terms(약관동의) 화면설계
> 시작일 : 2023.02.25
> 예상 종료일 : 2023.02.25
> 실제 종료일: 
> 후기 :

**Comment by 094haley** [comment]
** 회원 약관동의 화면설계**

- [ ] 약관 목록
- [ ] 회원가입 버튼
