### ISSUE TITLE
[화면구현] 회원 > signup(일반회원가입)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#7]

**Comment by 094haley** [comment]
** 회원 일반회원가입 화면설계**
> 담당자 : 이해빈
> 내용 : 회원 signup(일반회원가입) 화면설계
> 시작일 : 2023/02/25
> 예상 종료일 : 2023/02/26
> 실제 종료일: 
> 후기 :

**Comment by 094haley** [comment]
**체크리스트**

- [ ] 이메일 아이디
- [ ] 인증번호 제한시간 3분 display
- [ ] 비밀번호 / 비밀번호 확인
- [ ] 닉네임
- [ ] 최종 가입하기 버튼
