### ISSUE TITLE
[화면구현] 회원 > singnup(비지니스회원가입)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#8]

**Comment by 094haley** [comment]
**회원 비즈니스 회원가입 화면설계**
> 담당자 : 이해빈
> 내용 : 회원 signup(비즈니스 회원가입) 화면설계
> 시작일 : 2023/02/26
> 예상 종료일 : 2023/02/26
> 실제 종료일: 
> 후기 :

**Comment by 094haley** [comment]
**체크리스트**

- [ ] 회사명
- [ ] 개업일자
- [ ] 사업자 등록번호
- [ ] 대표자 이름
- [ ] 회사 이메일
- [ ] 회사 전화번호
- [ ] 주소
