### ISSUE TITLE
[화면구현] 회원 > resetPw(비밀번호 재설정)

### ISSUE THREAD

**Issue by ooo3345sjh** [ooo3345sjh/LeMo#9]

**Comment by 094haley** [comment]
**회원 비밀번호 재설정 화면설계**

> 담당자 : 이해빈
> 내용 : 회원 resetPW(비밀번호 재설정) 화면설계
> 시작일 : 2023/02/26
> 예상 종료일 : 2023/02/26
> 실제 종료일:  
> 후기 :

**Comment by 094haley** [comment]
**체크리스트**

- [ ] 이메일 아이디, 인증번호

- [ ] 비밀번호, 비밀번호 확인

**Comment by 094haley** [comment]
**기능구현시 참고사항**
